#!/usr/bin/env python3
"""
Scrape Data Quality Report Generator.
Phase 2 - DataTrust OS v4.0

Reads all scraped CSVs from data/scraped/*.csv and generates data/scraped/SCRAPE_REPORT.md
Analyzing review counts, rating distribution, teen-code density, and teen-code examples.
"""

import glob
import os
import re

import pandas as pd

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRAPED_DIR = os.path.join(PROJECT_ROOT, "data", "scraped")
REPORT_PATH = os.path.join(SCRAPED_DIR, "SCRAPE_REPORT.md")

TEENCODE_KEYWORDS = [
    r"\bvl\b", r"\bvcl\b", r"\bphet\b", r"\bphết\b", r"\bko\b", r"\bk\b", r"\bj\b", r"\bz\b",
    r"\bhp\b", r"\bgv\b", r"\bktx\b", r"\bsv\b", r"\bcmnr\b", r"\bcc\b", r"sh\*t",
    r"\bphap\b", r"\bdk\b", r"\bmệt vl\b", r"\bdinh\b"
]
TEENCODE_PATTERN = re.compile("|".join(TEENCODE_KEYWORDS), re.IGNORECASE)


def is_teencode(text: str) -> bool:
    if not isinstance(text, str):
        return False
    return bool(TEENCODE_PATTERN.search(text))


def generate_scrape_report():
    os.makedirs(SCRAPED_DIR, exist_ok=True)
    csv_files = glob.glob(os.path.join(SCRAPED_DIR, "*.csv"))

    if not csv_files:
        print(f"[REPORT ERROR] No scraped CSV files found in {SCRAPED_DIR}")
        return

    all_dfs = []
    source_stats = {}

    for fpath in csv_files:
        fname = os.path.basename(fpath)
        df = pd.read_csv(fpath)
        source_name = df["source"].iloc[0] if ("source" in df.columns and not df.empty) else os.path.splitext(fname)[0]
        source_stats[fname] = {
            "source": source_name,
            "count": len(df),
            "columns": list(df.columns)
        }
        all_dfs.append(df)

    combined_df = pd.concat(all_dfs, ignore_index=True)
    total_reviews = len(combined_df)

    # Calculate Teen-code Density
    combined_df["has_teencode"] = combined_df["review_text"].astype(str).apply(is_teencode)
    teencode_count = combined_df["has_teencode"].sum()
    teencode_density = (teencode_count / total_reviews * 100) if total_reviews > 0 else 0.0

    # Rating distribution
    rating_counts = combined_df["rating"].value_counts().sort_index(ascending=True).to_dict()

    # Collect 10 sample teen-code reviews
    teencode_samples = combined_df[combined_df["has_teencode"]].head(10)

    # Format Markdown Report
    markdown_content = []
    markdown_content.append("# 📊 DataTrust OS v4.0 — Scraped Feedback Data Quality Report\n")
    markdown_content.append(f"**Generated Date:** `{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}`  ")
    markdown_content.append(f"**Directory:** `{SCRAPED_DIR}`  ")
    markdown_content.append(f"**Total Scraped Files:** `{len(csv_files)}`  ")
    markdown_content.append(f"**Total Feedback Reviews:** `{total_reviews}`  \n")

    markdown_content.append("---")
    markdown_content.append("## 1. 📂 Review Counts by Source File\n")
    markdown_content.append("| File Name | Source Name | Total Reviews | Columns |")
    markdown_content.append("|---|---|---|---|")
    for fname, info in source_stats.items():
        cols_str = ", ".join(info["columns"])
        markdown_content.append(f"| `{fname}` | `{info['source']}` | **{info['count']}** | `{cols_str}` |")
    markdown_content.append(f"| **Total** | — | **{total_reviews}** | — |\n")

    markdown_content.append("---")
    markdown_content.append("## 2. 🔤 Vietnamese Teen-Code Slang Density Analysis\n")
    markdown_content.append(f"- **Teen-Code Keyword Patterns:** `vl`, `vcl`, `phet`, `ko`, `j`, `z`, `hp`, `gv`, `ktx`, `sv`, `cmnr`, `cc`, `sh*t`, etc.")
    markdown_content.append(f"- **Reviews Containing Teen-Code:** **{teencode_count}** / {total_reviews}")
    markdown_content.append(f"- **Estimated Teen-Code Density:** **{teencode_density:.2f}%**\n")

    markdown_content.append("---")
    markdown_content.append("## 3. ⭐ Rating Distribution\n")
    markdown_content.append("| Rating Star | Count | Percentage |")
    markdown_content.append("|---|---|---|")
    for star in sorted(rating_counts.keys()):
        cnt = rating_counts[star]
        pct = (cnt / total_reviews * 100) if total_reviews > 0 else 0.0
        markdown_content.append(f"| ⭐ **{star:.1f}** | {cnt} | {pct:.2f}% |")
    markdown_content.append("\n---")

    markdown_content.append("## 4. 📝 10 Sample Vietnamese Teen-Code Reviews\n")
    markdown_content.append("| # | Source | Rating | Category / Location | Review Text |")
    markdown_content.append("|---|---|---|---|---|")
    for i, (_, row) in enumerate(teencode_samples.iterrows(), 1):
        cat_loc = row.get("category", row.get("location", "N/A"))
        markdown_content.append(f"| {i} | `{row.get('source', 'n/a')}` | ⭐ {row.get('rating', 0.0)} | `{cat_loc}` | *\"{row.get('review_text', '')}\"* |")

    markdown_content.append("\n---\n*Report auto-generated by `scripts/generate_scrape_report.py` for Phase 2 DataTrust OS v4.0.*")

    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(markdown_content))

    print(f"[REPORT SUCCESS] Generated SCRAPE_REPORT.md at {REPORT_PATH}")
    print(f"[REPORT SUMMARY] Total Reviews: {total_reviews}, Teen-Code Density: {teencode_density:.2f}% ({teencode_count}/{total_reviews})")


if __name__ == "__main__":
    generate_scrape_report()
