"""
DataTrust OS: Internal Agent Proposal Syntax Validator
IMPORTANT HITL GOVERNANCE RULE:
This validator is strictly an INTERNAL prompt/syntax check for agent proposals
PRIOR to creating a ProposedRuleModel (status='PENDING').
It NEVER directly modifies, writes, or applies rules to Lane B!
All rule activation requires human admin review and approval.
"""

import ast
import re
from typing import Dict, Any, Tuple


class ProposalSyntaxValidator:
    """Validates the syntax and parameter validity of rule proposals internally generated by agents."""

    VALID_OPERATIONS = {
        "mask_phone", "mask_name", "mask_email", "mask_vin",
        "redact_null", "round_decimal", "hash_sha256", "range_check",
        "to_upper", "to_lower", "clamp_numeric"
    }

    @classmethod
    def validate_proposal(
        cls,
        operation_id: str,
        params: Dict[str, Any],
        expression_display: str
    ) -> Tuple[bool, str]:
        """
        Validates internal agent proposal before submitting it as PENDING.
        Returns:
            (is_valid, error_message_or_empty)
        """
        # 1. Operation ID check
        if operation_id not in cls.VALID_OPERATIONS:
            return False, f"Thao tác '{operation_id}' không nằm trong danh mục các phép biến đổi được hỗ trợ."

        # 2. Parameter schema validation
        if operation_id == "round_decimal":
            decimals = params.get("decimals")
            if decimals is None or not isinstance(decimals, int) or decimals < 0 or decimals > 6:
                return False, "round_decimal yêu cầu tham số 'decimals' là số nguyên từ 0 đến 6."

        elif operation_id == "range_check":
            min_val = params.get("min_val")
            max_val = params.get("max_val")
            if min_val is None and max_val is None:
                return False, "range_check yêu cầu ít nhất 'min_val' hoặc 'max_val'."
            if min_val is not None and max_val is not None and min_val > max_val:
                return False, f"min_val ({min_val}) không thể lớn hơn max_val ({max_val})."

        elif operation_id == "mask_phone":
            prefix = params.get("prefix_len", 3)
            suffix = params.get("suffix_len", 2)
            if not isinstance(prefix, int) or not isinstance(suffix, int) or prefix < 0 or suffix < 0:
                return False, "mask_phone yêu cầu prefix_len và suffix_len là số nguyên không âm."

        # 3. Expression safety & syntax verification via AST
        if expression_display:
            try:
                # Wrap simplified expressions in a safe dummy statement for AST check
                test_expr = expression_display.replace("BETWEEN", "and").replace("AND", "and")
                # Remove SQL-style keywords if any
                clean_expr = re.sub(r"\b(IN|NOT IN|IS NOT NULL|IS NULL)\b", "==", test_expr, flags=re.IGNORECASE)
                ast.parse(clean_expr)
            except SyntaxError:
                # If complex SQL syntax, perform basic parenthesis and character balance check
                if expression_display.count("(") != expression_display.count(")"):
                    return False, f"Biểu thức '{expression_display}' không cân bằng dấu ngoặc đơn."

        return True, ""
