import type { ComponentProps } from 'react';
import { Link as RouterLink } from 'react-router-dom';
import { ChevronRight, Filter, Play, Search, Workflow } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import type { PipelineRun } from '@/lib/data/pipeline-types';
import { PipelineStatusBadge } from './pipeline-status';
function Link({href,...props}:Omit<ComponentProps<typeof RouterLink>,'to'>&{href:string}){return <RouterLink to={href} {...props}/>}
const format=(value:string)=>new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
export function PipelineRuns({runs}:{runs:PipelineRun[]}){return <section className="page-enter mx-auto max-w-[1440px] space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.14em] text-blue-600">Data Pipeline</p><h1 className="text-2xl font-bold tracking-tight">Pipeline Runs</h1><p className="mt-1 text-sm text-slate-500">Monitor pipeline execution, record movement, and quality outcomes.</p></div><Button size="sm"><Play size={14}/> Run pipeline</Button></div><Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14}/><input className="h-9 w-full rounded-md border border-slate-200 bg-slate-50 pl-9 pr-3 text-xs" placeholder="Search run or DAG..."/></div><button className="flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-xs text-slate-600"><Filter size={13}/> All statuses</button></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="border-b border-slate-200 bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr>{['Run ID','DAG ID','Status','Input records','Silver records','Quarantine records','Started at','Duration',''].map((column,index)=><th key={`${column}-${index}`} className="px-4 py-3 font-semibold">{column}</th>)}</tr></thead><tbody>{runs.map(run=><tr key={run.id} className="group border-b border-slate-100 last:border-0 hover:bg-blue-50/40"><td className="px-4 py-3"><Link href={`/pipeline-runs/${run.id}`} className="font-semibold text-blue-600 hover:underline">{run.id}</Link></td><td className="px-4 py-3 font-medium"><span className="inline-flex items-center gap-2"><Workflow size={13} className="text-slate-400"/>{run.dagId}</span></td><td className="px-4 py-3"><PipelineStatusBadge status={run.status}/></td><td className="px-4 py-3">{run.inputRecords.toLocaleString()}</td><td className="px-4 py-3">{run.silverRecords.toLocaleString()}</td><td className="px-4 py-3"><span className={run.quarantineRecords?'font-medium text-amber-600':'text-slate-500'}>{run.quarantineRecords.toLocaleString()}</span></td><td className="whitespace-nowrap px-4 py-3 text-slate-500">{format(run.startedAt)}</td><td className="px-4 py-3 text-slate-500">{run.durationMinutes} min</td><td className="px-4 py-3"><Link href={`/pipeline-runs/${run.id}`} aria-label={`Open ${run.id}`}><ChevronRight size={16} className="text-slate-300 group-hover:text-blue-600"/></Link></td></tr>)}</tbody></table></div><div className="border-t border-slate-200 px-4 py-3 text-xs text-slate-500">{runs.length} pipeline runs</div></Card></section>}
