#!/usr/bin/env python3
"""
Compiler Tool for the DataTrust OS pipeline (Step 4).

Takes declarative rules (scripts/rules.json) that pass the Validator Tool
(scripts/validate_rules.py) and compiles each one into two representations:
  - satisfies_expr: a Python boolean expression a row must satisfy to pass
    the rule, e.g. "battery_soc >= 0 and battery_soc <= 100"
  - violation_sql:  a SQL WHERE clause that finds the rows that VIOLATE the
    rule (the logical negation), e.g. "WHERE battery_soc < 0 OR battery_soc > 100"

It only compiles rules to text. It does not run them against source.db and
does not touch any data — execution is the Executor's job in a later step.
Invalid rules (per the Validator) are skipped and reported, never compiled.

Usage:
  python scripts/compile_rules.py [--rules scripts/rules.json]
                                   [--schema data/profiling_report.json]
                                   [--out-prefix data/compiled_rules]
"""
import argparse
import json
from pathlib import Path

from validate_rules import load_rules, load_schema, validate_rule

REPO_ROOT = Path(__file__).resolve().parent.parent


def format_sql_literal(value) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def format_py_literal(value) -> str:
    return repr(value)


def compile_rule(rule: dict) -> dict:
    operator = rule["operator"]
    column = rule["column"]
    value = rule.get("value")

    if operator == "not_null":
        satisfies = f"{column} is not None"
        violation = f"{column} IS NULL"

    elif operator == "gte":
        satisfies = f"{column} >= {value}"
        violation = f"{column} < {value}"

    elif operator == "lte":
        satisfies = f"{column} <= {value}"
        violation = f"{column} > {value}"

    elif operator == "gt":
        satisfies = f"{column} > {value}"
        violation = f"{column} <= {value}"

    elif operator == "lt":
        satisfies = f"{column} < {value}"
        violation = f"{column} >= {value}"

    elif operator == "eq":
        satisfies = f"{column} == {format_py_literal(value)}"
        violation = f"{column} <> {format_sql_literal(value)}"

    elif operator == "ne":
        satisfies = f"{column} != {format_py_literal(value)}"
        violation = f"{column} = {format_sql_literal(value)}"

    elif operator == "between":
        lo, hi = value
        satisfies = f"{column} >= {lo} and {column} <= {hi}"
        violation = f"{column} < {lo} OR {column} > {hi}"

    elif operator == "in":
        satisfies = f"{column} in {format_py_literal(value)}"
        sql_list = ", ".join(format_sql_literal(v) for v in value)
        violation = f"{column} NOT IN ({sql_list})"

    elif operator == "regex":
        satisfies = f"re.match({format_py_literal(value)}, str({column})) is not None"
        violation = f"NOT ({column} REGEXP {format_sql_literal(value)})"

    elif operator == "expr_eq":
        tolerance = rule.get("tolerance", 0)
        satisfies = f"abs({column} - ({value})) <= {tolerance}"
        violation = f"ABS({column} - ({value})) > {tolerance}"

    elif operator == "is_numeric":
        satisfies = f"isinstance({column}, (int, float))"
        violation = f"typeof({column}) = 'text'"

    elif operator == "valid_date":
        satisfies = f"re.match(r'^\\d{{4}}-\\d{{2}}-\\d{{2}}T\\d{{2}}:\\d{{2}}:\\d{{2}}', str({column})) is not None"
        glob_pattern = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]*"
        violation = f"{column} IS NOT NULL AND {column} NOT GLOB '{glob_pattern}'"

    else:
        raise ValueError(f"cannot compile unknown operator '{operator}'")

    return {
        "rule_id": rule["rule_id"],
        "table": rule["table"],
        "column": column,
        "operator": operator,
        "description": rule.get("description", ""),
        "satisfies_expr": satisfies,
        "violation_sql": f"WHERE {violation}",
    }


def render_markdown(compiled: list[dict], skipped: list[dict]) -> str:
    lines = [
        "# Compiled Rules",
        "",
        "Generated by `scripts/compile_rules.py` from `scripts/rules.json`.",
        "These are text representations only — nothing here has been executed.",
        "",
        f"**{len(compiled)} rules compiled, {len(skipped)} skipped (invalid).**",
        "",
    ]
    for c in compiled:
        lines.append(f"## {c['rule_id']} — {c['table']}.{c['column']}")
        lines.append("")
        if c["description"]:
            lines.append(f"> {c['description']}")
            lines.append("")
        lines.append("```python")
        lines.append(f"# satisfies (row passes the rule)")
        lines.append(c["satisfies_expr"])
        lines.append("```")
        lines.append("")
        lines.append("```sql")
        lines.append(f"-- violations (rows that fail the rule)")
        lines.append(f"SELECT * FROM {c['table']}")
        lines.append(c["violation_sql"])
        lines.append("```")
        lines.append("")

    if skipped:
        lines.append("## Skipped (invalid rules, not compiled)")
        lines.append("")
        lines.append("| Rule ID | Table | Column | Reason |")
        lines.append("|---|---|---|---|")
        for s in skipped:
            lines.append(f"| {s['rule_id']} | {s['table']} | {s['column']} | {'; '.join(s['errors'])} |")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rules", default="scripts/rules.json")
    parser.add_argument("--schema", default="data/profiling_report.json")
    parser.add_argument("--out-prefix", default="data/compiled_rules")
    args = parser.parse_args()

    schema = load_schema(REPO_ROOT / args.schema)
    rules = load_rules(REPO_ROOT / args.rules)

    compiled, skipped = [], []
    for rule in rules:
        errors = validate_rule(rule, schema)
        if errors:
            skipped.append({"rule_id": rule.get("rule_id", "?"), "table": rule.get("table", "?"),
                             "column": rule.get("column", "?"), "errors": errors})
            print(f"[SKIP] {rule.get('rule_id', '?'):<10} invalid: {'; '.join(errors)}")
            continue

        c = compile_rule(rule)
        compiled.append(c)
        print(f"[OK]   {c['rule_id']:<10} {c['satisfies_expr']}")
        print(f"                  {c['violation_sql']}")

    json_path = REPO_ROOT / f"{args.out_prefix}.json"
    md_path = REPO_ROOT / f"{args.out_prefix}.md"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(compiled, indent=2, ensure_ascii=False), encoding="utf-8")
    md_path.write_text(render_markdown(compiled, skipped), encoding="utf-8")

    print(f"\n{len(compiled)} rules compiled, {len(skipped)} skipped.")
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
