#!/usr/bin/env python3
"""
Profiler Tool for the DataTrust OS pipeline (Step 2).

Reads every table in data/source.db (built by scripts/build_source_db.py)
and returns schema + metadata only, per table:
  - record count / column count
  - column names, declared SQLite type, observed pandas dtype
  - per-column NULL count / rate
  - per-column distinct value count
  - duplicate record count (full row, excluding the primary key)
  - primary key columns

Anomaly/invalid-value detection (outliers, invalid dates, type mismatches,
constraint-rule violations) is out of scope here — that belongs to the
downstream Anomaly Engine / Rule Engine stage, not the Profiler.

Usage:
  python scripts/profile_source_db.py [--db data/source.db] [--out-prefix data/profiling_report]
"""
import argparse
import json
import sqlite3
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent


def get_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence'"
    ).fetchall()
    return [r[0] for r in rows]


def get_pk_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    info = conn.execute(f"PRAGMA table_info({table})").fetchall()
    pk_cols = [(row[5], row[1]) for row in info if row[5] > 0]  # (pk order, name)
    return [name for _, name in sorted(pk_cols)]


def get_declared_types(conn: sqlite3.Connection, table: str) -> dict[str, str]:
    info = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return {row[1]: row[2] for row in info}


def profile_table(conn: sqlite3.Connection, table: str) -> dict:
    df = pd.read_sql_query(f"SELECT * FROM {table}", conn)
    row_count, col_count = df.shape
    pk_cols = get_pk_columns(conn, table)
    declared_types = get_declared_types(conn, table)

    columns_report = []
    for col in df.columns:
        series = df[col]
        null_count = int(series.isna().sum())
        columns_report.append(
            {
                "column": col,
                "declared_type": declared_types.get(col, ""),
                "observed_dtype": str(series.dtype),
                "null_count": null_count,
                "null_rate": round(null_count / row_count, 4) if row_count else 0.0,
                "distinct_count": int(series.nunique(dropna=True)),
            }
        )

    compare_cols = [c for c in df.columns if c not in pk_cols] or list(df.columns)
    duplicate_count = int(df.duplicated(subset=compare_cols).sum())

    return {
        "table": table,
        "row_count": row_count,
        "column_count": col_count,
        "primary_key": pk_cols,
        "duplicate_count": duplicate_count,
        "columns": columns_report,
    }


def log_table_summary(report: dict) -> None:
    print(f"\n=== {report['table']} ===")
    print(f"  rows={report['row_count']}  columns={report['column_count']}  pk={report['primary_key'] or '(none)'}")
    print(f"  duplicate_records={report['duplicate_count']}")
    for col in report["columns"]:
        null_str = f"null={col['null_count']}({col['null_rate']:.1%})" if col["null_count"] else ""
        print(
            f"    {col['column']:<24} {col['declared_type']:<8} distinct={col['distinct_count']:<6} {null_str}"
        )


def render_markdown(reports: list[dict]) -> str:
    lines = ["# Data Profiling Report", "", "Generated by `scripts/profile_source_db.py` from `data/source.db`.", ""]
    lines.append("## Summary")
    lines.append("")
    lines.append("| Table | Rows | Columns | Duplicates | Primary Key |")
    lines.append("|---|---:|---:|---:|---|")
    for r in reports:
        lines.append(
            f"| {r['table']} | {r['row_count']} | {r['column_count']} | {r['duplicate_count']} | {', '.join(r['primary_key']) or '-'} |"
        )
    lines.append("")

    for r in reports:
        lines.append(f"## {r['table']}")
        lines.append("")
        lines.append(f"- Primary key: `{', '.join(r['primary_key']) or '(none)'}`")
        lines.append(f"- Rows: {r['row_count']}, Columns: {r['column_count']}")
        lines.append(f"- Duplicate records (excl. PK): {r['duplicate_count']}")
        lines.append("")
        lines.append("| Column | Declared Type | Observed dtype | Null rate | Distinct |")
        lines.append("|---|---|---|---:|---:|")
        for col in r["columns"]:
            lines.append(
                "| {column} | {declared_type} | {observed_dtype} | {null_rate:.1%} | {distinct_count} |".format(
                    **col
                )
            )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default="data/source.db")
    parser.add_argument("--out-prefix", default="data/profiling_report")
    args = parser.parse_args()

    db_path = REPO_ROOT / args.db
    conn = sqlite3.connect(db_path)
    try:
        reports = []
        for table in get_tables(conn):
            report = profile_table(conn, table)
            log_table_summary(report)
            reports.append(report)
    finally:
        conn.close()

    json_path = REPO_ROOT / f"{args.out_prefix}.json"
    md_path = REPO_ROOT / f"{args.out_prefix}.md"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(reports, indent=2, ensure_ascii=False), encoding="utf-8")
    md_path.write_text(render_markdown(reports), encoding="utf-8")

    print(f"\nWrote {json_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
