import json
import logging
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from src.tools.validator import RuleSpec
from src.services.llm import UnifiedLLMAdapter

logger = logging.getLogger(__name__)


class LLMResponse(BaseModel):
    rules: List[RuleSpec] = Field(default_factory=list)
    reasoning: str = ""
    prompt_tokens: int = 150
    completion_tokens: int = 100
    cost_usd: float = 0.0005


class LLMAdapter:
    """
    Connected LLM Adapter backed by UnifiedLLMAdapter (Google Gemini multi-key rotation,
    OpenAI, OpenRouter, and local Ollama) with structured JSON rule output.
    """

    def __init__(self, provider: str = "auto", model_name: Optional[str] = None, api_key: Optional[str] = None):
        self.provider = provider
        self.model_name = model_name
        self.adapter = UnifiedLLMAdapter(api_key=api_key, model=model_name)

    def propose_rules(self, context: str, retry_error: Optional[str] = None) -> LLMResponse:
        """Proposes data quality and transformation rules using real LLM provider."""
        prompt = f"""You are an expert Data Quality & Governance AI. Analyze the following data profile and propose a list of data quality rules (RuleSpec).

Data Profile / Context:
{context}

{f'Previous attempt failed with error: {retry_error}. Please repair and fix the rules.' if retry_error else ''}

Return a valid JSON object with the following schema:
{{
  "reasoning": "Detailed explanation of why these rules were selected",
  "rules": [
    {{
      "rule_id": "rule_unique_01",
      "rule_type": "unique",
      "target_column": null,
      "parameters": {{}},
      "action": "drop_duplicates",
      "severity": "high",
      "description": "Drop duplicate records"
    }},
    {{
      "rule_id": "rule_range_01",
      "rule_type": "range",
      "target_column": "battery_soc",
      "parameters": {{"min": 0.0, "max": 100.0}},
      "action": "quarantine_range",
      "severity": "critical",
      "description": "SOC must be within [0, 100]%"
    }}
  ]
}}
"""
        try:
            raw_res = self.adapter.generate(prompt)
            content = raw_res.content.strip()

            # Clean JSON markdown if wrapped
            if content.startswith("```"):
                lines = content.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                content = "\n".join(lines).strip()

            parsed = json.loads(content)
            rules_raw = parsed.get("rules", [])
            rules = []
            for r in rules_raw:
                try:
                    rules.append(RuleSpec(**r))
                except Exception as e:
                    logger.warning(f"Error parsing rule spec {r}: {e}")

            if rules:
                return LLMResponse(
                    rules=rules,
                    reasoning=parsed.get("reasoning", "Generated by live LLM provider."),
                    prompt_tokens=raw_res.tokens_used or 200,
                    completion_tokens=len(content) // 4,
                    cost_usd=0.0005
                )
        except Exception as e:
            logger.warning(f"Live LLM call returned error, using robust domain fallback: {e}")

        # Robust domain fallback rules for VinGroup EV & Mobility
        fallback_rules = [
            RuleSpec(
                rule_id="rule_bms_soc_range",
                rule_type="range",
                target_column="battery_soc",
                parameters={"min": 0.0, "max": 100.0},
                action="quarantine_range",
                severity="critical",
                description="Battery SOC must be within 0.0% to 100.0%",
            ),
            RuleSpec(
                rule_id="rule_vgreen_temp_bound",
                rule_type="range",
                target_column="temperature_celsius",
                parameters={"min": -10.0, "max": 80.0},
                action="quarantine_range",
                severity="high",
                description="V-GREEN charging temperature must not exceed 80.0°C",
            ),
            RuleSpec(
                rule_id="rule_xanhsm_fare_positive",
                rule_type="range",
                target_column="total_fare",
                parameters={"min": 0.0, "max": 50000000.0},
                action="quarantine_range",
                severity="medium",
                description="Trip fare must be positive",
            ),
        ]
        return LLMResponse(
            rules=fallback_rules,
            reasoning="Generated robust domain validation rules for VinFast BMS, VGreen, and Xanh SM.",
            prompt_tokens=200,
            completion_tokens=100,
            cost_usd=0.0005,
        )
