'use client';
import { useState } from 'react';
import type { ComponentProps } from 'react';
import { Link as RouterLink } from 'react-router-dom';
import { ArrowLeft, Bot, Check, CheckCircle2, Clipboard, Clock3, ExternalLink, Link2, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { FindingDetail as FindingDetailModel } from '@/lib/data/findings-types';
import { SeverityBadge, StateBadge } from './finding-badges';

const tabs = ['Overview','Evidence','Processing History','AI Assistant','Related'] as const;
type Tab = typeof tabs[number];
function Link({href,...props}:Omit<ComponentProps<typeof RouterLink>,'to'>&{href:string}){return <RouterLink to={href} {...props}/>}
const displayDate = (value:string) => new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));

export function FindingDetail({ finding }: { finding: FindingDetailModel }) {
  const [tab,setTab]=useState<Tab>('Overview');
  return <section className="page-enter mx-auto max-w-[1440px] space-y-5">
    <div><Link href="/findings" className="mb-4 inline-flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-blue-600"><ArrowLeft size={14}/> Findings</Link><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight">{finding.id}</h1><SeverityBadge value={finding.severity}/><StateBadge value={finding.status}/></div><p className="mt-1 text-sm text-slate-600">{finding.title}</p></div><Button size="sm">Update status</Button></div></div>
    <div className="flex gap-1 overflow-x-auto border-b border-slate-200">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?'whitespace-nowrap border-b-2 border-blue-600 px-4 py-3 text-xs font-semibold text-blue-600':'whitespace-nowrap border-b-2 border-transparent px-4 py-3 text-xs font-medium text-slate-500 hover:text-slate-800'}>{item}{item==='Evidence'&&<span className="ml-1">({finding.evidence.length})</span>}{item==='Related'&&<span className="ml-1">({finding.related.length})</span>}</button>)}</div>
    {tab==='Overview'&&<Overview finding={finding}/>} {tab==='Evidence'&&<Evidence finding={finding} onRelatedControl={()=>setTab('Overview')}/>} {tab==='Processing History'&&<History finding={finding}/>} {tab==='AI Assistant'&&<Assistant/>} {tab==='Related'&&<Related finding={finding}/>} 
  </section>;
}

function Overview({finding}:{finding:FindingDetailModel}) { return <div className="grid gap-4 lg:grid-cols-[340px_1fr]"><Card><CardHeader><CardTitle>Finding metadata</CardTitle></CardHeader><CardContent className="space-y-4">{[['Finding ID',finding.id],['Control domain',finding.domain],['Assigned to',finding.assignedTo],['Created at',displayDate(finding.createdAt)]].map(([label,value])=><div key={label} className="grid grid-cols-[110px_1fr] gap-3 text-xs"><span className="text-slate-400">{label}</span><strong className="font-medium text-slate-700">{value}</strong></div>)}</CardContent></Card><div className="space-y-4"><Card><CardHeader><CardTitle>Violated control</CardTitle></CardHeader><CardContent><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-red-50 text-red-600"><ShieldAlert size={18}/></span><div><p className="text-xs font-semibold text-blue-600">{finding.control.id}</p><p className="mt-1 text-sm font-semibold">{finding.control.name}</p><p className="mt-2 text-xs leading-5 text-slate-500">{finding.control.evaluationMessage}</p></div></div></CardContent></Card><Card><CardContent className="grid gap-6 p-5 md:grid-cols-2"><TextSection title="Issue description" text={finding.issueDescription}/><TextSection title="Impact" text={finding.impact}/><div className="md:col-span-2"><h3 className="mb-3 text-sm font-semibold">Recommended actions</h3><ol className="space-y-2">{finding.recommendedActions.map((action,index)=><li key={action} className="flex gap-3 text-xs leading-5 text-slate-600"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-blue-50 text-[10px] font-bold text-blue-600">{index+1}</span>{action}</li>)}</ol></div></CardContent></Card></div></div>; }
function TextSection({title,text}:{title:string;text:string}) { return <div><h3 className="mb-2 text-sm font-semibold">{title}</h3><p className="text-xs leading-5 text-slate-600">{text}</p></div>; }
function Evidence({finding,onRelatedControl}:{finding:FindingDetailModel;onRelatedControl:()=>void}) {
  const [selectedId,setSelectedId]=useState(finding.evidence[0]?.id ?? '');
  const [copied,setCopied]=useState(false);
  const selected=finding.evidence.find(item=>item.id===selectedId);
  const copyEvidence=async()=>{if(!selected)return;await navigator.clipboard.writeText(JSON.stringify({evidence_id:selected.id,source_system:selected.source,evidence_type:selected.type,timestamp:selected.capturedAt,actor:selected.actor,linked_object:selected.linkedObject,raw_reference:selected.reference,raw_event:selected.rawEvent},null,2));setCopied(true);window.setTimeout(()=>setCopied(false),1600);};
  if(!finding.evidence.length) return <Card><CardContent className="py-14 text-center text-sm text-slate-400">No linked evidence was recorded.</CardContent></Card>;
  return <div className="space-y-4"><Card className="overflow-hidden"><CardHeader><CardTitle>Linked evidence</CardTitle><span className="text-[11px] text-slate-400">{finding.evidence.length} item{finding.evidence.length===1?'':'s'}</span></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-y border-slate-200 bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr>{['Evidence ID','Source system','Evidence type','Timestamp','Actor','Linked object','Raw reference'].map(column=><th key={column} className="px-4 py-3 font-semibold">{column}</th>)}</tr></thead><tbody>{finding.evidence.map(item=><tr key={item.id} onClick={()=>setSelectedId(item.id)} className={selectedId===item.id?'cursor-pointer border-b border-blue-100 bg-blue-50/70':'cursor-pointer border-b border-slate-100 hover:bg-slate-50'}><td className="px-4 py-3 font-semibold text-blue-600">{item.id}</td><td className="px-4 py-3 text-slate-600">{item.source}</td><td className="px-4 py-3"><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-medium text-slate-600">{item.type}</span></td><td className="px-4 py-3 whitespace-nowrap text-slate-500">{displayDate(item.capturedAt)}</td><td className="px-4 py-3 font-medium">{item.actor}</td><td className="px-4 py-3 text-slate-600">{item.linkedObject}</td><td className="px-4 py-3 font-mono text-[10px] text-slate-500">{item.reference}</td></tr>)}</tbody></table></CardContent></Card>
  {selected&&<Card><CardHeader><div><CardTitle>Evidence viewer · {selected.id}</CardTitle><p className="mt-1 text-[11px] text-slate-400">Structured source event from {selected.reference}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={copyEvidence}>{copied?<Check size={13}/>:<Clipboard size={13}/>} {copied?'Copied':'Copy evidence'}</Button><Button variant="outline" size="sm" onClick={()=>setSelectedId(selected.id)}><ExternalLink size={13}/> View raw event</Button><Button variant="outline" size="sm" onClick={onRelatedControl}><ShieldAlert size={13}/> Related control result · {selected.controlResultId}</Button></div></CardHeader><CardContent><div className="overflow-x-auto rounded-lg border border-slate-800 bg-[#0b1624] p-4"><pre className="min-w-[620px] whitespace-pre-wrap font-mono text-[11px] leading-5 text-emerald-300">{JSON.stringify(selected.rawEvent,null,2)}</pre></div><div className="mt-3 grid gap-3 text-[11px] sm:grid-cols-3"><div><span className="text-slate-400">Integrity source</span><p className="mt-1 font-mono text-slate-600">{selected.reference}</p></div><div><span className="text-slate-400">Actor</span><p className="mt-1 font-medium">{selected.actor}</p></div><div><span className="text-slate-400">Linked object</span><p className="mt-1 font-medium">{selected.linkedObject}</p></div></div></CardContent></Card>}</div>;
}
function History({finding}:{finding:FindingDetailModel}) { return <Card><CardHeader><CardTitle>Processing history</CardTitle></CardHeader><CardContent><div className="space-y-0">{finding.history.map((item,index)=><div key={`${item.label}-${index}`} className="flex gap-4"><div className="flex flex-col items-center"><span className={item.tone==='green'?'grid size-8 place-items-center rounded-full bg-emerald-50 text-emerald-600':item.tone==='amber'?'grid size-8 place-items-center rounded-full bg-amber-50 text-amber-600':'grid size-8 place-items-center rounded-full bg-blue-50 text-blue-600'}>{item.tone==='green'?<CheckCircle2 size={15}/>:<Clock3 size={15}/>}</span>{index<finding.history.length-1&&<span className="h-12 w-px bg-slate-200"/>}</div><div><p className="text-xs font-semibold">{item.label}</p><p className="mt-1 text-xs text-slate-500">{item.detail}</p><p className="mt-1 text-[10px] text-slate-400">{displayDate(item.occurredAt)}</p></div></div>)}</div></CardContent></Card>; }
function Assistant() { return <Card><CardContent className="flex min-h-64 flex-col items-center justify-center p-8 text-center"><span className="grid size-12 place-items-center rounded-xl bg-blue-50 text-blue-600"><Bot size={22}/></span><h3 className="mt-4 text-sm font-semibold">AI Assistant</h3><p className="mt-2 max-w-md text-xs leading-5 text-slate-500">Ask for a risk summary, evidence analysis, or remediation plan. Assistant integration will connect to the platform service in a later milestone.</p></CardContent></Card>; }
function Related({finding}:{finding:FindingDetailModel}) { return <Card><CardHeader><CardTitle>Related findings</CardTitle></CardHeader><CardContent className="space-y-2">{finding.related.length?finding.related.map(item=><Link key={item.id} href={`/findings/${item.id}`} className="flex items-center gap-3 rounded-lg border border-slate-200 p-4 hover:border-blue-200 hover:bg-blue-50/40"><Link2 className="text-blue-600" size={16}/><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-blue-600">{item.id}</p><p className="truncate text-xs text-slate-600">{item.title}</p></div><SeverityBadge value={item.severity}/><StateBadge value={item.status}/></Link>):<p className="py-8 text-center text-sm text-slate-400">No related findings.</p>}</CardContent></Card>; }
